name: 'Comment GitHub Actions link to PR'
description: 'PRをmainにマージしたときにmain branchのon pushで走り出したデプロイワークフローのリンクをもとのPRに貼る'

runs:
  using: composite
  steps:
    - name: Get PR number
      shell: bash
      run: echo "PR_NUMBER=$(git log --format=%B -n 1 | grep 'Merge pull request' | awk '{print $4}' | cut -d'#' -f2)" >> $GITHUB_ENV

    - name: Add comment to PR
      if: env.PR_NUMBER
      uses: actions/github-script@v6
      with:
        script: |
          const pr_number = process.env.PR_NUMBER;
          const action_url = `https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
          const comment_body = `Action "${workflow_name}" has started on main branch after merging this PR. [Check the workflow here](${action_url}).`;
          github.rest.issues.createComment({
            issue_number: pr_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment_body
          });
