name: receiver_deploy
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world"

  comment_gha_link_to_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/comment-gha-link-to-pr
