name: receiver_deploy
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world"

  comment_gha_link_to_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/comment-gha-link-to-pr
